import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../app/globals.css";
import { Header } from "@/_app/components/common";
import { ScrollingContextProvider } from "@/_app/context/ScrollingContext";
import { useLocale } from "next-globe-gen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: { template: "%s | Brite Cap", default: "Brite Cap" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollingContextProvider>
          <Header />
          <main>{children}</main>
        </ScrollingContextProvider>
      </body>
    </html>
  );
}
